### ISSUE TITLE
Energy Integration of home assistant

### ISSUE THREAD

**Issue by andsk8** [thomluther/hacs-anker-solix#104]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Not really, and maybe it was discussed before, but integration with Solarbank 2 works now, but still I cant add the solar production for example to the energy integration of home assistant. I understand theres something with templates and overrides but im unsure what to set and where. Is there some general guidance to be able to integrate the solar production, the power consumption and the home battery storage?

### Describe the solution you'd like

The lines to add in the configuration.yml file

### Describe alternatives you've considered

Tried template and sensor override with no luck

### Additional context

If this was mentioned before or in another repo, im sorry, I tried to look for it and couldnt find it.

**Comment by thomluther** [comment]
@andsk8 
Please have a look to this [discussion ](https://github.com/thomluther/hacs-anker-solix/discussions/16)where you should find the answer to your question.
I close this issue accordingly, you can follow up in the discussion topic if necessary
