### ISSUE TITLE
Compatibility to ioBroker

### ISSUE THREAD

**Issue by robbieffm** [thomluther/hacs-anker-solix#28]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I'm a fan of your project on GitHub, but as an ioBroker user, I'd love to see it compatible for installation through ioBroker. Could you extend support beyond HACS to include ioBroker?

### Describe the solution you'd like

compatible for installation through ioBroker

### Describe alternatives you've considered

 compatible for installation through ioBroker

### Additional context

thank you

**Comment by thomluther** [comment]
Hi, unfortunately not. I'm not familiar with IO Broker and not going to invest time to it.
You better go to find someone using the Api python library as base for Iobroker Adapter
